<?php

########################################################################
# Extension Manager/Repository config file for ext: "heap_search"
#
# Auto generated by Extension Builder 2016-01-01
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Heap Search',
	'description' => 'Search content with help of HEAP tables',
	'category' => 'plugin',
	'author' => 'Stefan Froemken',
	'author_email' => 'froemken@gmail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.0.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);